nodeLinker: node-modules
pnpMode: loose
checksumBehavior: update

packageExtensions:
  "prettier@*":
    dependencies:
      "@babel/parser": "*"
      "@babel/core": "*"
  "stylelint-order@*":
    dependencies:
      "postcss": "*"
      "postcss-scss": "*"
  "stylelint@*":
    dependencies:
      "postcss": "*"
      "postcss-scss": "*"
  "stylelint-prettier@*":
    dependencies:
      "prettier-linter-helpers": "*"